### ISSUE TITLE
After npm start > Login > Token issue

### ISSUE THREAD

**Issue by MichaelWalker-git** [Azure-Samples/ms-identity-javascript-nodejs-tutorial#38]
# Issue

```
ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.
    at ClientAuthError.AuthError [as constructor] (/Users/michaelwalker/WebstormProjects/ms-identity-javascript-nodejs-tutorial/2-Authorization/1-call-graph/App/node_modules/@azure/msal-common/dist/index.cjs.js:477:24)
```
<img width="1710" alt="Screen Shot 2022-04-13 at 5 53 24 AM" src="https://user-images.githubusercontent.com/11032490/163184320-6d84cbcb-1b1b-4472-abfd-bd4a756656d6.png">

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [x ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ]   3) Deploy to Azure Storage and App Service
    - [ ] 4-1) Use App Roles for Role-based Access Control
    - [ ] 4-2) Use Security Groups for Role-based Access Control
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ x] documentation issue or request
```

### Minimal steps to reproduce

> Input all necessary appSettiings.js things
> Go to http://localhost:4000/home
> Click Signin > Finish Oauth flow > Error Page

### Any log messages given by the failure

> See above

### Expected/desired behavior

> Match screen shot in readme

### Library version

> Most recent

### Browser and version

> Chrome, Edge, Firefox, Safari?

- Chrome
### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by MichaelWalker-git** [comment]
Any updates?

**Comment by salman90** [comment]
Hi @MichaelWalker-git  
Can you please share the logs, the request calls, and the appSettings object?
