### ISSUE TITLE
Error: No error route provided!

### ISSUE THREAD

**Issue by jungyou87** [Azure-Samples/ms-identity-javascript-nodejs-tutorial#40]
# Issue

> Please provide us with the following information:
When I tried to run locally after app registration and appSetting configuration, I get error.
Error: No error route provided!

## This issue is for the sample

```console
    - [X] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ]   3) Deploy to Azure Storage and App Service
    - [ ] 4-1) Use App Roles for Role-based Access Control
    - [ ] 4-2) Use Security Groups for Role-based Access Control
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [X] documentation issue or request
```

### Minimal steps to reproduce

> Follow the instruction for 1-1 sign in Authentication

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by SameerK-MSFT** [comment]
+1. Having the same issue.

**Comment by derisen** [comment]
@jungyou87 @SameerK-MSFT I'm not able to reproduce this with a fresh clone. Do you, by chance, have an older version of the `microsoft-identity-express` package installed? Would you mind deleting your `package-lock.json` file and `node_modules` folder and do a clean install to try agan?

**Comment by SameerK-MSFT** [comment]
Created PR for it. Thanks @derisen for the tip. https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial/pull/42
