### ISSUE TITLE
Error on start page

### ISSUE THREAD

**Issue by RoqueMag** [Azure-Samples/ms-identity-javascript-nodejs-tutorial#41]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ]   3) Deploy to Azure Storage and App Service
    - [ ] 4-1) Use App Roles for Role-based Access Control
    - [x] 4-2) Use Security Groups for Role-based Access Control
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> All steps describle in https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial/blob/main/4-AccessControl/2-security-groups/README.md#running-the-sample.
Error in npm start

### Any log messages given by the failure

>npm start

> msal-node-tutorial-security-groups@1.0.0 start
> node app.js

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'jwks-rsa'
Require stack:
- C:\Geral\Func-React-WebApp\ms-identity-javascript-nodejs-tutorial-main\4-AccessControl\2-security-groups\App\node_modules\microsoft-identity-express\dist\microsoft-identity-express.cjs.development.js
- C:\Geral\Func-React-WebApp\ms-identity-javascript-nodejs-tutorial-main\4-AccessControl\2-security-groups\App\node_modules\microsoft-identity-express\dist\index.js
- C:\Geral\Func-React-WebApp\ms-identity-javascript-nodejs-tutorial-main\4-AccessControl\2-security-groups\App\app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Geral\Func-React-WebApp\ms-identity-javascript-nodejs-tutorial-main\4-AccessControl\2-security-groups\App\node_modules\microsoft-identity-express\dist\microsoft-identity-express.cjs.development.js:11:34)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Geral\\Func-React-WebApp\\ms-identity-javascript-nodejs-tutorial-main\\4-AccessControl\\2-security-groups\\App\\node_modules\\microsoft-identity-express\\dist\\microsoft-identity-express.cjs.development.js',
    'C:\\Geral\\Func-React-WebApp\\ms-identity-javascript-nodejs-tutorial-main\\4-AccessControl\\2-security-groups\\App\\node_modules\\microsoft-identity-express\\dist\\index.js',
    'C:\\Geral\\Func-React-WebApp\\ms-identity-javascript-nodejs-tutorial-main\\4-AccessControl\\2-security-groups\\App\\app.js'
  ]
}

Re-Install and Re-start

new error:
 npm start

> msal-node-tutorial-signin@1.0.0 start
> node app.js

C:\Geral\Func-React-WebApp\ms-identity-javascript-nodejs-tutorial-main\1-Authentication\1-sign-in\App\node_modules\microsoft-identity-express.cjs.development.js:1056
      throw new Error(ConfigurationErrorMessages.NO_ERROR_ROUTE);
      ^

Error: No error route provided!

Create node in App\appSettings.js

error: "/error",

    authRoutes: {
        redirect: "/redirect",
        error: "/error",
        unauthorized: "/unauthorized" // the wrapper will redirect to this route in case of unauthorized access attempt.
    }

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Edge

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@RoqueMag I believe you have an older version of `microsoft-identity-express` (I see that `package.json` does not specify the exact version). Can you try deleting your `package-lock.json` file and `node_modules` folder, and then do a clean install to try again?

I'll make a PR to update the `package-lock.json` files. Apologies for the hassle.

**Comment by SameerK-MSFT** [comment]
@RoqueMag I had the same issue. Fixed in this PR: https://github.com/Azure-Samples/ms-identity-javascript-nodejs-tutorial/pull/42.
